### ISSUE TITLE
Request: Webpack bundle for use in client-side web browsers

### ISSUE THREAD

**Issue by diadal** [warren-bank/ethereumjs-tx-sign#1] opened 2018-01-02 16:33 UTC
Uncaught Error: Cannot find module '@warren-bank/ethereumjs-tx-sign'
 
any solution for this error report

**Comment by warren-bank** [comment] 2018-01-02 17:34
Hi. I wasn't able to reproduce any error:

```bash
#!/usr/bin/env bash

cd ~

git clone https://github.com/warren-bank/ethereumjs-tx-sign.git
cd ethereumjs-tx-sign
npm install
cd tests/04_README_examples
rm run.log
./run.sh
cat run.log
```

The above simply downloads the repo and runs the sample code included in the README. The output looks good.

Is there any chance that the module that your project cannot find is something unrelated to this particular library? Maybe you're calling `require()` to some module that isn't installed? [ESLint](https://eslint.org/) might be [helpful](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md) to you.

**Comment by diadal** [comment] 2018-01-02 19:22
still same error please check below code if any error

<script type="text/javascript" src="/web3.js/dist/web3.js"></script>
<script type="text/javascript">
    
const {sign} = require('ethereumjs-tx-sign')

const txData = {
  nonce:    '0x00',
  gasPrice: '0x6fc23ac00',
  gasLimit: '0x2710',
//to:       '0x00',
  value:    '0x00',
  data:     '0x7f7465737432000000000000000000000000000000000000000000000000000000600057',
  chainId:  1
}

const privateKey = 'e922354a3e5902b5ac474f3ff08a79cff43533826b8f451ae2190b65a9d26158'

const {rawTx} = sign(txData, privateKey)

const Web3 = require('web3')
const web3 = new Web3()
web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'))

web3.eth.sendRawTransaction(rawTx, function(err, hash) {
  if (err)
    console.log('error:', err.message)
  if ((!err) && hash)
    console.log('transaction hash:', hash)
})

</script>

**Comment by warren-bank** [comment] 2018-01-02 19:56
There appears to be one fundamental flaw with your code. It assumes that web browsers share the exact same execution environment as node.js. There is a lot of overlap in native APIs between the two environments, allowing for many isomorphic libraries to be written that can run equally well in either. However, there are some APIs that are native to one but not the other, which makes it challenging to write universal libraries; sets of polyfills becomes necessary.. one set for each execution environment that doesn't include all of the necessary native APIs; each polyfill must function as a perfect drop-in replacement for its corresponding native API.

Sufficed to say, this repo doesn't include a release that contains a browser-ready bundle. The npm module is intended for a node.js execution environment. Though Webpack could be used to build such a bundle, there would probably be a lot of imported modules that are natively available in node.js (ex: Buffer) that would need to be polyfilled and included as additional dependencies. I haven't made any such attempt.

If such a bundle were created, then the library would be made available as a global variable; you wouldn't call `require()` in the browser.. unless you were feeling masochistic and also included some kind of client-side module loader (ex: require.js).

In any case, this feels off-topic to me. Its not an issue with the library itself, but rather a request that it be released in an additional format.. one that can be loaded directly into a web browser.

I'll leave this issue open and change its title to reflect your request. If a decent number other users give the issue a "+1".. then I'll look into preparing such a bundle.

Of course, if anyone wants to offer a pull request that includes a directory structure along the lines of:
```text
./browser-build/
./browser-build/package.json
./browser-build/webpack.config.js
./browser-build/dist/js/
./browser-build/dist/js/bundle.js
```
..then I'd be glad to fast track its adoption.

**Comment by warren-bank** [comment] 2018-01-03 04:10
I was just hanging around the house, so I figured that I'd go ahead and package this up..

Commit [b7756a0](https://github.com/warren-bank/ethereumjs-tx-sign/commit/b7756a012613fee3eb26a472faafaf6444df32d1) pushes both:
* the plumbing to generate a fresh Webpack bundle
* the client-side bundle

The [README](https://github.com/warren-bank/ethereumjs-tx-sign#browser-bundle) includes a super quick summary of what globals are made available.

I ported over 2 of the tests. If you compare the node.js version to the client-side version, you'll see that the only change is how the library methods are accessed. Once references to them are saved in local variables, the code works exactly the same in both execution environments.

note: I cheated a little.. I'm also running Babel client-side, so the ES2015 code in both of the test cases could be used verbatim.. without being transpiled ahead of time.

The README includes links to both of these tests. They're hosted on a public server, so you can run them locally in your favorite web browser.

**Closed as completed** 2018-01-03 04:12 UTC
